
// This file has been generated by the GUI designer. Do not modify.
namespace InterpreterCSharpGUIFinal
{
	public partial class DeserializeWindow
	{
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textView;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Button deserializeButton;
		
		private global::Gtk.Button backButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget InterpreterCSharpGUIFinal.DeserializeWindow
			this.Name = "InterpreterCSharpGUIFinal.DeserializeWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("DeserializeWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child InterpreterCSharpGUIFinal.DeserializeWindow.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			this.vbox6.BorderWidth = ((uint)(6));
			// Container child vbox6.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Deserialization Output");
			this.vbox6.Add (this.label7);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label7]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textView = new global::Gtk.TextView ();
			this.textView.CanFocus = true;
			this.textView.Name = "textView";
			this.textView.Editable = false;
			this.textView.CursorVisible = false;
			this.GtkScrolledWindow.Add (this.textView);
			this.vbox6.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Homogeneous = true;
			this.hbox5.Spacing = 6;
			this.hbox5.BorderWidth = ((uint)(6));
			// Container child hbox5.Gtk.Box+BoxChild
			this.deserializeButton = new global::Gtk.Button ();
			this.deserializeButton.CanFocus = true;
			this.deserializeButton.Name = "deserializeButton";
			this.deserializeButton.UseUnderline = true;
			this.deserializeButton.Label = global::Mono.Unix.Catalog.GetString ("Deserialize");
			this.hbox5.Add (this.deserializeButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.deserializeButton]));
			w4.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.backButton = new global::Gtk.Button ();
			this.backButton.CanFocus = true;
			this.backButton.Name = "backButton";
			this.backButton.UseUnderline = true;
			this.backButton.Label = global::Mono.Unix.Catalog.GetString ("Back");
			this.hbox5.Add (this.backButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.backButton]));
			w5.Position = 1;
			this.vbox6.Add (this.hbox5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox5]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.vbox6);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 771;
			this.DefaultHeight = 501;
			this.Show ();
			this.deserializeButton.Clicked += new global::System.EventHandler (this.OnDeserializeButtonClicked);
			this.backButton.Clicked += new global::System.EventHandler (this.OnBackButtonClicked);
		}
	}
}
