
// This file has been generated by the GUI designer. Do not modify.
namespace InterpreterCSharpGUIFinal
{
	public partial class OneStepWindow
	{
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textview2;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Button oneStepButton;
		
		private global::Gtk.Button backButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget InterpreterCSharpGUIFinal.OneStepWindow
			this.Name = "InterpreterCSharpGUIFinal.OneStepWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("OneStepWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child InterpreterCSharpGUIFinal.OneStepWindow.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			this.vbox4.BorderWidth = ((uint)(6));
			// Container child vbox4.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("One Step Output");
			this.vbox4.Add (this.label5);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label5]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview2 = new global::Gtk.TextView ();
			this.textview2.CanFocus = true;
			this.textview2.Name = "textview2";
			this.textview2.Editable = false;
			this.textview2.CursorVisible = false;
			this.GtkScrolledWindow.Add (this.textview2);
			this.vbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 6;
			this.hbox3.BorderWidth = ((uint)(6));
			// Container child hbox3.Gtk.Box+BoxChild
			this.oneStepButton = new global::Gtk.Button ();
			this.oneStepButton.CanFocus = true;
			this.oneStepButton.Name = "oneStepButton";
			this.oneStepButton.UseUnderline = true;
			this.oneStepButton.Label = global::Mono.Unix.Catalog.GetString ("One Step");
			this.hbox3.Add (this.oneStepButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.oneStepButton]));
			w4.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.backButton = new global::Gtk.Button ();
			this.backButton.CanFocus = true;
			this.backButton.Name = "backButton";
			this.backButton.UseUnderline = true;
			this.backButton.Label = global::Mono.Unix.Catalog.GetString ("Back");
			this.hbox3.Add (this.backButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.backButton]));
			w5.Position = 1;
			this.vbox4.Add (this.hbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 745;
			this.DefaultHeight = 523;
			this.Show ();
			this.oneStepButton.Clicked += new global::System.EventHandler (this.OnOneStepButtonClicked);
			this.backButton.Clicked += new global::System.EventHandler (this.OnBackButtonClicked);
		}
	}
}
