
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Button insertProgramButton;
	
	private global::Gtk.Button oneStepButton;
	
	private global::Gtk.Button allStepButton;
	
	private global::Gtk.Button serializeButton;
	
	private global::Gtk.Button deserializeButton;
	
	private global::Gtk.CheckButton logCheckBox;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(6));
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Choose Option :");
		this.vbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.insertProgramButton = new global::Gtk.Button ();
		this.insertProgramButton.CanFocus = true;
		this.insertProgramButton.Name = "insertProgramButton";
		this.insertProgramButton.UseUnderline = true;
		this.insertProgramButton.Label = global::Mono.Unix.Catalog.GetString ("Insert Program");
		this.vbox1.Add (this.insertProgramButton);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.insertProgramButton]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.oneStepButton = new global::Gtk.Button ();
		this.oneStepButton.CanFocus = true;
		this.oneStepButton.Name = "oneStepButton";
		this.oneStepButton.UseUnderline = true;
		this.oneStepButton.Label = global::Mono.Unix.Catalog.GetString ("One Step");
		this.vbox1.Add (this.oneStepButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.oneStepButton]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.allStepButton = new global::Gtk.Button ();
		this.allStepButton.CanFocus = true;
		this.allStepButton.Name = "allStepButton";
		this.allStepButton.UseUnderline = true;
		this.allStepButton.Label = global::Mono.Unix.Catalog.GetString ("All Step");
		this.vbox1.Add (this.allStepButton);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.allStepButton]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.serializeButton = new global::Gtk.Button ();
		this.serializeButton.CanFocus = true;
		this.serializeButton.Name = "serializeButton";
		this.serializeButton.UseUnderline = true;
		this.serializeButton.Label = global::Mono.Unix.Catalog.GetString ("Serialize");
		this.vbox1.Add (this.serializeButton);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.serializeButton]));
		w5.Position = 4;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.deserializeButton = new global::Gtk.Button ();
		this.deserializeButton.CanFocus = true;
		this.deserializeButton.Name = "deserializeButton";
		this.deserializeButton.UseUnderline = true;
		this.deserializeButton.Label = global::Mono.Unix.Catalog.GetString ("Deserialize");
		this.vbox1.Add (this.deserializeButton);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.deserializeButton]));
		w6.Position = 5;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.logCheckBox = new global::Gtk.CheckButton ();
		this.logCheckBox.CanFocus = true;
		this.logCheckBox.Name = "logCheckBox";
		this.logCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Log to \"log.txt\"");
		this.logCheckBox.DrawIndicator = true;
		this.logCheckBox.UseUnderline = true;
		this.vbox1.Add (this.logCheckBox);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.logCheckBox]));
		w7.Position = 6;
		w7.Expand = false;
		w7.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 222;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.insertProgramButton.Clicked += new global::System.EventHandler (this.OnInsertProgramButtonClicked);
		this.oneStepButton.Clicked += new global::System.EventHandler (this.OnOneStepButtonClicked);
		this.allStepButton.Clicked += new global::System.EventHandler (this.OnAllStepButtonClicked);
		this.serializeButton.Clicked += new global::System.EventHandler (this.OnSerializeButtonClicked);
		this.deserializeButton.Clicked += new global::System.EventHandler (this.OnDeserializeButtonClicked);
		this.logCheckBox.Clicked += new global::System.EventHandler (this.OnLogCheckBoxClicked);
	}
}
